function(find_spdlog shm_server_root)
	if (NOT DEFINED SPDLOG_SRC_DIR)
		set(SPDLOG_SRC_DIR "${shm_server_root}/dependencies/spdlog")
	endif()
	include(${SPDLOG_SRC_DIR}/cmake/utils.cmake)
	set(CURRENT_DIR ${CMAKE_CURRENT_LIST_DIR})
	set(CMAKE_CURRENT_LIST_DIR ${SPDLOG_SRC_DIR})
	spdlog_extract_version()
	set(CMAKE_CURRENT_LIST_DIR ${CURRENT_DIR})
	MESSAGE(STATUS "looking for spdlog ${SPDLOG_VERSION}")
	find_package(spdlog ${SPDLOG_VERSION} QUIET)
	if (NOT spdlog_FOUND)
		MESSAGE(STATUS "looking for spdlog - not found")
		set(SPDLOG_BUILD_SHARED ON)
		add_subdirectory(${SPDLOG_SRC_DIR})
	else()
		MESSAGE(STATUS "looking for spdlog - found")
	endif()
endfunction()
